parameters:
  - name: subscription
    type: string

steps:
  # Instalar Terraform
  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: latest

  # Instalar Terragrunt
  - bash: |
      echo "Installing Terragrunt..."
      if [ -z "${TERRAGRUNT_VERSION}" ]; then
          URL="https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64"
      else
          URL="https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64"
      fi
      wget $URL && \
      mv terragrunt_linux_amd64 terragrunt && \
      chmod +x terragrunt && \
      sudo mv terragrunt /usr/local/bin
    displayName: Install Terragrunt

  # # Autenticar con Azure y establecer variables ARM
  # - task: AzureCLI@2
  #   displayName: Authenticate with Azure
  #   inputs:
  #     azureSubscription: ${{ parameters.subscription }}
  #     scriptType: bash
  #     scriptLocation: inlineScript
  #     addSpnToEnvironment: true
  #     inlineScript: |
  #       echo "Authenticating with Azure..."
  #       export ARM_SUBSCRIPTION_ID=$(az account show --query id --output tsv)
  #       export ARM_CLIENT_ID=$servicePrincipalId
  #       export ARM_CLIENT_SECRET=$servicePrincipalKey
  #       export ARM_TENANT_ID=$tenantId
  #       echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
  #       echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
  #       echo "ARM_TENANT_ID: $ARM_TENANT_ID"
  #       echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$ARM_SUBSCRIPTION_ID"
  #       echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$ARM_CLIENT_ID"
  #       echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$ARM_CLIENT_SECRET"
  #       echo "##vso[task.setvariable variable=ARM_TENANT_ID]$ARM_TENANT_ID"
