---

parameters:
  - name: subscription
    type: string
steps:
  - task: TerraformInstaller@1
    displayName: install terraform
    inputs:
      terraformVersion: latest
  - bash: |
      if [ -z "${TERRAGRUNT_VERSION}" ]; then
          URL="https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64"
      else
          URL="https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64"
      fi
      wget $URL && \
      mv terragrunt_linux_amd64 terragrunt && \
      chmod +x terragrunt && \
      sudo mv terragrunt /usr/local/bin
    displayName: Install Terragrunt
  - task: AzureCLI@2
    displayName: Authenticate Terraform
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      azureSubscription: ${{parameters.subscription}}
      addSpnToEnvironment: true
      inlineScript: |
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id --output tsv)"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
