trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

pr: none

variables:
  - group: AzureServiceConnectionProd

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: deploy_infrastructure
    displayName: "Deploy Infrastructure Changes to PROD"
    steps:
      # Install tools and authenticate
      - template: ../templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_PROD)

      # Generate plan
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/prod
          terragrunt run-all plan -out=prod.tfplan
        displayName: "Plan Infrastructure Changes for PROD"
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)

      # Apply plan
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/prod
          terragrunt run-all apply prod.tfplan --terragrunt-non-interactive
        displayName: "Apply Infrastructure Changes to PROD"
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
