# src/api/pipelines/ci-build.yml
trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-24.04'

variables:
  BUILD_CONFIGURATION: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'src/api/TheFullStackTeam.Backend.sln'
      # workingDirectory: '$(System.DefaultWorkingDirectory)/src/api'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'src/api/TheFullStackTeam.Backend.sln'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src/api'
      arguments: '--configuration $(BUILD_CONFIGURATION)'
