version: '3.4'

services:
  thefullstackteam.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=7100
      - ASPNETCORE_HTTPS_PORT=7101

    volumes:
        # Mapea la carpeta local de User Secrets al contenedor Docker (solo lectura)
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        # Mapea los certificados HTTPS desde la carpeta local al contenedor Docker (solo lectura)
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro