name: API CI

on:
  push:
    paths:
      - 'API/**'
  pull_request:
    paths:
      - 'API/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: adminpassword
          POSTGRES_DB: fullstackteamdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore API/TheFullStackTeam.API

      - name: Build API
        run: dotnet build --no-restore API/TheFullStackTeam.API

      - name: Run API Tests
        run: dotnet test --no-build API/tests
