trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - src/api/**

pr: none

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: deploy_api
    displayName: "Deploy API to DEV"
    steps:
      # 1. Authenticate and initialize Terraform
      - template: ../templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
      
      # 2. Initialize Terragrunt Dependencies
      - bash: |
          echo "Initializing Terragrunt dependencies"
          cd "$(System.DefaultWorkingDirectory)/infrastructure/envs/dev"
          terragrunt run-all init -reconfigure
        displayName: "Initialize Terragrunt Dependencies"
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)

      # 3. Fetch App Service Name
      - template: ../templates/fetch_app_service_name.yml
        parameters:
          terragrunt_path: infrastructure/envs/dev/app_services/api

      # 4. Publish .NET Solution
      - task: DotNetCoreCLI@2
        displayName: 'Publish .NET Solution'
        inputs:
          command: 'publish'
          projects: 'src/api/TheFullStackTeam.Backend.sln'
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/src/api'

      # 5. Verify Artifact Directory
      - bash: |
          echo "Contents of $(Build.ArtifactStagingDirectory):"
          ls -al $(Build.ArtifactStagingDirectory)
        displayName: "List Artifact Directory"

      # 6. Create Deployment ZIP
      - task: ArchiveFiles@2
        displayName: 'Create Deployment ZIP'
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/api-deployment.zip'
          replaceExistingArchive: true

      # 7. Deploy API to App Service
      - task: AzureWebApp@1
        displayName: "Deploy API to App Service"
        inputs:
          azureSubscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
          appType: 'webApp'
          appName: $(APP_SERVICE_NAME)
          package: '$(Build.ArtifactStagingDirectory)/api-deployment.zip'
