# devops/azure-pipelines/api/api-ci-dev.yml
# This file contains the pipeline definition for building the API in the DEV environment.

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - src/api/**

pool:
  vmImage: 'ubuntu-24.04'

steps:
- task: UseDotNet@2
  displayName: 'Set up .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- checkout: self
  displayName: 'Checkout code from repository'

- task: DotNetCoreCLI@2  
  displayName: 'Restore .NET packages'
  inputs:
    command: 'restore'
    projects: 'src/api/TheFullStackTeam.Backend.sln'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/api'

- task: DotNetCoreCLI@2
  displayName: 'Build .NET Solution'
  inputs:
    command: 'build'
    projects: 'src/api/TheFullStackTeam.Backend.sln'
    arguments: '--configuration Release'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/api'    