trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - src/webapp/**

pr: none

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: deploy_webapp
    displayName: "Deploy WebApp to DEV"
    steps:
      # 1. Authenticate and initialize Terraform for infrastructure
      - template: ../templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)

      # 2. Initialize Terragrunt dependencies (App Service for WebApp)
      - bash: |
          echo "Initializing Terragrunt dependencies for WebApp..."
          cd "$(System.DefaultWorkingDirectory)/infrastructure/envs/dev/app_services/webapp"
          terragrunt run-all init -reconfigure --terragrunt-non-interactive
        displayName: "Initialize Terragrunt Dependencies for WebApp"
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)

      # 3. Fetch App Service Name for WebApp
      - template: ../templates/fetch_app_service_name.yml
        parameters:
          terragrunt_path: infrastructure/envs/dev/app_services/webapp

      # 4. Install Node.js for Angular 18.x+
      - task: NodeTool@0
        displayName: "Install Node.js 18.x for Angular"
        inputs:
          versionSpec: '18.x'
          checkLatest: true

      # 5. Build Angular application
      - bash: |
          echo "Installing npm dependencies..."
          cd $(System.DefaultWorkingDirectory)/src/webapp/TFST-Front
          npm install
        displayName: "Install npm dependencies"

      - bash: |
          echo "Building Angular application for production..."
          cd $(System.DefaultWorkingDirectory)/src/webapp/TFST-Front
          npm run build --prod
        displayName: "Build Angular Application"

      # 6. Verify build output directory
      - bash: |
          echo "Listing contents of the build output directory..."
          ls -al $(System.DefaultWorkingDirectory)/src/webapp/TFST-Front/dist/tfst-front
        displayName: "Verify Build Output Directory"

      # 7. Prepare the build artifacts for deployment (compress to zip)
      - bash: |
          echo "Compressing build artifacts into a zip file..."
          cd $(System.DefaultWorkingDirectory)/src/webapp/TFST-Front/dist/tfst-front
          zip -r $(Build.ArtifactStagingDirectory)/webapp.zip .
        displayName: "Compress Build Artifacts"

      # 8. Verify compressed artifact
      - bash: |
          echo "Verifying the compressed artifact..."
          ls -al $(Build.ArtifactStagingDirectory)
        displayName: "Verify Compressed Artifact"

      # 9. Deploy WebApp to Azure App Service
      - task: AzureWebApp@1
        displayName: "Deploy WebApp to Azure App Service"
        inputs:
          azureSubscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
          appType: 'webApp'
          appName: $(APP_SERVICE_NAME_WEBAPP)
          package: '$(Build.ArtifactStagingDirectory)/webapp.zip'
