trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: validate_infrastructure
    displayName: "Validate Terraform & Terragrunt"
    steps:
      # Instalar herramientas y autenticar
      - template: ../pipeline_templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
      
      # Validar formato Terraform
      - bash: terraform fmt -recursive -check $(System.DefaultWorkingDirectory)/infrastructure/modules
        displayName: "Terraform FMT modules"

      # Validar sintaxis de Terragrunt
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure
          terragrunt hclfmt --terragrunt-check
        displayName: "Terragrunt HCL FMT"

      # Validar infraestructura
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/dev
          terragrunt run-all validate
        displayName: "Terragrunt Validate"
