trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionProd

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: validate_infrastructure
    displayName: "Validate Terraform & Terragrunt" 
    steps:
      # Install tools and authenticate
      - template: ../pipeline_templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_PROD)
      
      # Validate Terraform modules
      - bash: terraform fmt -recursive -check $(System.DefaultWorkingDirectory)/infrastructure/modules
        displayName: "Validate Terraform Syntax"

      # Validate Terragrunt syntax
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure
          terragrunt hclfmt --terragrunt-check
        displayName: "Validate Terragrunt Syntax"

      # Validate infrastructure code
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/prod
          terragrunt run-all validate
        displayName: "Validate Infrastructure Code"
        # Inject environment variables from Library Variable Group(s)
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
