trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-22.04

jobs:
  # Job para validar módulos de Terraform y Terragrunt
  - job: validate_terraform_modules
    displayName: Check formatting of *.tf and *.hcl files
    steps:
      - template: ../pipeline_templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)

      # Verificar el formato de los archivos Terraform
      - bash: terraform fmt -recursive -check $(System.DefaultWorkingDirectory)/infrastructure/modules
        displayName: Terraform FMT modules

      # Validar la sintaxis de Terragrunt
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure
          terragrunt hclfmt --terragrunt-check
        displayName: Terragrunt HCL FMT

  # Job para validar la infraestructura en el entorno dev
  - job: validate_terraform_dev
    displayName: Validate Terraform scripts (dev)
    dependsOn: validate_terraform_modules
    steps:
      - template: ../pipeline_templates/terraform_validate_scripts.yml
        parameters:
          env: dev
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
