trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: deploy_infrastructure
    displayName: "Deploy Terraform & Terragrunt"
    steps:
      # Install tools and authenticate
      - template: ../pipeline_templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)

      # Generate plan
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/dev
          terragrunt run-all plan -out=dev.tfplan
        displayName: "Plan Infrastructure Changes"

      # Apply plan
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/dev
          terragrunt run-all apply dev.tfplan -auto-approve
        displayName: "Apply Infrastructure Changes"
        
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
