trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: ValidateAndDeploy
    displayName: "Validate and Deploy Infrastructure"
    jobs:
      - job: validate_infrastructure
        displayName: "Validate Infrastructure"
        steps:
          - template: infrastructure/pipeline_templates/terraform_validate_scripts.yml
            parameters:
              env: dev
              subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)

      - job: deploy_infrastructure
        displayName: "Deploy Infrastructure"
        dependsOn: validate_infrastructure
        condition: succeeded()
        steps:
          - bash: |
              cd infrastructure/envs/dev
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
