trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: validate_azure_infrastructure
    displayName: Validate Infrastructure Configuration
    jobs:
      # Validar m贸dulos de Terraform y Terragrunt
      - job: validate_terraform_modules
        displayName: Check formatting of *.tf and *.hcl files
        steps:
          - template: ../pipeline_templates/terragrunt_init.yml
            parameters:
              subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)

          - bash: terraform fmt -recursive -check $(System.DefaultWorkingDirectory)/infrastructure/modules
            displayName: Terraform FMT modules

          - bash: |
              cd $(System.DefaultWorkingDirectory)/infrastructure
              terragrunt hclfmt --terragrunt-check
            displayName: Terragrunt HCL FMT

      # Validaci贸n para el entorno dev
      - template: ../pipeline_templates/terraform_validate_scripts.yml
        parameters:
          env: dev
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
          dependsOn: validate_terraform_modules

      # Validaci贸n para el entorno staging
      - template: ../pipeline_templates/terraform_validate_scripts.yml
        parameters:
          env: staging
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
          dependsOn: validate_terraform_modules

      # Validaci贸n para el entorno prod
      - template: ../pipeline_templates/terraform_validate_scripts.yml
        parameters:
          env: prod
          subscription: $(SERVICE_CONNECTION_NAME_ARM_PROD)
          dependsOn: validate_terraform_modules
