trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/**

variables:
  - group: AzureServiceConnectionDev

pool:
  vmImage: ubuntu-24.04

jobs:
  - job: validate_infrastructure
    displayName: "Validate Terraform & Terragrunt"
    steps:
      # Install tools and authenticate
      - template: ../pipeline_templates/terragrunt_init.yml
        parameters:
          subscription: $(SERVICE_CONNECTION_NAME_ARM_DEV)
      
      # Validate Terraform modules
      - bash: terraform fmt -recursive -check $(System.DefaultWorkingDirectory)/infrastructure/modules
        displayName: "Validate Terraform Syntax"

      # Validate Terragrunt syntax
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure
          terragrunt hclfmt --terragrunt-check
        displayName: "Validate Terragrunt Syntax"

      # Validate infrastructure code
      - bash: |
          cd $(System.DefaultWorkingDirectory)/infrastructure/envs/dev
          terragrunt run-all validate
        displayName: "Validate Infrastructure Code"