# .github/workflows/api-dev-cd.yml
name: Deploy API to DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/api/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: dev
      branch: dev
      working_directory: infrastructure/envs/dev/app_services/api
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
