# .github/workflows/api-dev-cd.yml
name: Deploy API to DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/api/**'

  workflow_dispatch:

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: dev
      branch: dev
      working_directory: src/api
      solution_name: TheFullStackTeam.Backend.sln
      app_service_name: tfst-api-dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
