# .github/workflows/infra-prod-deploy.yml
name: Deploy Infrastructure to PROD

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  deploy_prod_infra:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environment: prod
      working_directory: infrastructure/envs/prod      
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
