
# .github/workflows/infra-dev-deploy.yml
name: Deploy Infrastructure to DEV

on:
  push:
    branches:
      - dev
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  deploy_dev_infra:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      working_directory: infrastructure/envs/dev
    secrets:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
