# .github/workflows/infra-prod-validation.yml
name: Validate Infrastructure for PROD

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  validate_prod_infra:
    uses: ./.github/workflows/validate-infra.yml
    with:
      environment: prod
      working_directory: infrastructure/envs/prod
      terraform_modules_directory: infrastructure/modules
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

