# .github/workflows/infra-dev-validation.yml
name: Validate Infrastructure for DEV

on:
  push:
    branches:
      - dev
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  validate_dev_infra:
    uses: ./.github/workflows/validate-infra.yml
    with:
      environment: dev
      working_directory: infrastructure/envs/dev
      terraform_modules_directory: infrastructure/modules