
# .github/workflows/infra-dev-deploy.yml
name: Deploy Infrastructure to DEV

on:
  push:
    branches:
      - dev
    paths:
      - infrastructure/**

  workflow_dispatch:

jobs:
  deploy_dev_infra:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environment: dev
      working_directory: infrastructure/envs/dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

