# .github/workflows/validate-infra.yml
name: Validate Infrastructure

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        description: "The working directory for the environment (e.g., infrastructure/envs/dev)"
      terraform_modules_directory:
        required: true
        type: string
        description: "The directory for Terraform modules (e.g., infrastructure/modules)"
    secrets:
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  validate_infra:
    name: Validate Infrastructure
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Terraform and Terragrunt
      - name: Install Terraform and Terragrunt
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
          unzip -o terraform.zip -d /usr/local/bin/
          curl -fsSL https://github.com/gruntwork-io/terragrunt/releases/download/v0.69.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      # Validate Terraform syntax
      - name: Validate Terraform Syntax
        run: terraform fmt -recursive -check ${{ inputs.terraform_modules_directory }}

      # Validate Terragrunt syntax
      - name: Validate Terragrunt Syntax
        run: |
          cd ${{ inputs.working_directory }}
          terragrunt hclfmt --terragrunt-check

      # Validate Infrastructure Code
      - name: Validate Infrastructure Code
        run: |
          cd ${{ inputs.working_directory }}
          terragrunt run-all validate
